// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxy6JU3T3E8j0KaepO2TB7W9l-_dwsCY',
    appId: '1:977521016396:web:80f2df10a1e1d6c3bfbee9',
    messagingSenderId: '977521016396',
    projectId: 'stayswasth-ind',
    authDomain: 'stayswasth-ind.firebaseapp.com',
    storageBucket: 'stayswasth-ind.appspot.com',
    measurementId: 'G-4WQZH1KVMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxco12KY05V56nYztoGDF8wnz29xSrjVE',
    appId: '1:977521016396:android:437734b6520f06e7bfbee9',
    messagingSenderId: '977521016396',
    projectId: 'stayswasth-ind',
    storageBucket: 'stayswasth-ind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYuz2XkCIXcaxAhmUvm94ilwOQBsywNKY',
    appId: '1:977521016396:ios:72179fdfe41c8973bfbee9',
    messagingSenderId: '977521016396',
    projectId: 'stayswasth-ind',
    storageBucket: 'stayswasth-ind.appspot.com',
    iosBundleId: 'com.example.staySwasth',
  );
}
